//! Core backend abstraction: trait, parameter types, and error type.
//!
//! Every backend (LlamaBackend, MockBackend, or user-supplied) must implement
//! [`InferenceBackend`]. All methods are synchronous — callers are responsible
//! for dispatching to a blocking thread pool (e.g. `tokio::task::spawn_blocking`).

use std::path::Path;
use std::sync::mpsc;

#[cfg(feature = "llama")]
pub mod llama;
pub mod mock;

use crate::error::InferError;

/// Compute backend type for model inference.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BackendType {
    /// Apple Metal (macOS, Apple Silicon).
    Metal,
    /// Vulkan GPU (Windows / Linux, cross-vendor: NVIDIA / AMD / Intel).
    Vulkan,
    /// NVIDIA CUDA (Windows / Linux, opt-in legacy).
    Cuda,
    /// CPU fallback (all platforms).
    Cpu,
}

impl BackendType {
    /// Auto-detect the best available backend for the current platform.
    ///
    /// Detection logic (lightweight, non-blocking):
    ///
    /// | Priority | Platform        | Condition |
    /// |----------|-----------------|--------------------------------------------------|
    /// | 1        | macOS           | `metal` feature compiled in |
    /// | 2        | Windows + Linux | `vulkan` feature compiled in **and** Vulkan loader present |
    /// | 3        | Windows + Linux | `cuda` feature compiled in **and** NVIDIA driver present |
    /// | 4        | All             | Always available |
    pub fn auto_detect() -> Self {
        #[cfg(target_os = "macos")]
        let result = if cfg!(feature = "metal") {
            BackendType::Metal
        } else {
            BackendType::Cpu
        };

        #[cfg(target_os = "windows")]
        let result = detect_gpu_backend_windows();

        #[cfg(target_os = "linux")]
        let result = detect_gpu_backend_linux();

        #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
        let result = BackendType::Cpu;

        result
    }
}

/// Select the best GPU backend on Windows.
///
/// Priority: Vulkan (if feature + loader) → CUDA (if feature + driver) → CPU.
#[cfg(target_os = "windows")]
fn detect_gpu_backend_windows() -> BackendType {
    #[cfg(feature = "vulkan")]
    if has_vulkan_windows() {
        return BackendType::Vulkan;
    }
    #[cfg(feature = "cuda")]
    if has_nvidia_gpu_windows() {
        return BackendType::Cuda;
    }
    BackendType::Cpu
}

/// Select the best GPU backend on Linux.
///
/// Priority: Vulkan (if feature + loader) → CUDA (if feature + driver) → CPU.
#[cfg(target_os = "linux")]
fn detect_gpu_backend_linux() -> BackendType {
    #[cfg(feature = "vulkan")]
    if has_vulkan_linux() {
        return BackendType::Vulkan;
    }
    #[cfg(feature = "cuda")]
    if has_nvidia_gpu_linux() {
        return BackendType::Cuda;
    }
    BackendType::Cpu
}

/// Detect Vulkan loader on Windows by checking for `vulkan-1.dll` in System32.
#[cfg(all(target_os = "windows", feature = "vulkan"))]
fn has_vulkan_windows() -> bool {
    let system32 = std::env::var("SystemRoot")
        .map(|root| std::path::PathBuf::from(root).join("System32"))
        .unwrap_or_else(|_| std::path::PathBuf::from(r"C:\Windows\System32"));
    system32.join("vulkan-1.dll").exists()
}

/// Detect Vulkan loader on Linux by checking well-known library paths.
#[cfg(all(target_os = "linux", feature = "vulkan"))]
fn has_vulkan_linux() -> bool {
    [
        "/usr/lib/libvulkan.so.1",
        "/usr/lib64/libvulkan.so.1",
        "/lib/x86_64-linux-gnu/libvulkan.so.1",
        "/usr/lib/x86_64-linux-gnu/libvulkan.so.1",
    ]
    .iter()
    .any(|p| std::path::Path::new(p).exists())
}

/// Detect NVIDIA CUDA driver on Windows by checking for `nvcuda.dll` in System32.
#[cfg(all(target_os = "windows", feature = "cuda"))]
fn has_nvidia_gpu_windows() -> bool {
    let system32 = std::env::var("SystemRoot")
        .map(|root| std::path::PathBuf::from(root).join("System32"))
        .unwrap_or_else(|_| std::path::PathBuf::from(r"C:\Windows\System32"));
    system32.join("nvcuda.dll").exists()
}

/// Detect NVIDIA GPU on Linux by checking for the NVIDIA driver proc entry.
#[cfg(all(target_os = "linux", feature = "cuda"))]
fn has_nvidia_gpu_linux() -> bool {
    std::path::Path::new("/proc/driver/nvidia/version").exists()
}

impl std::fmt::Display for BackendType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BackendType::Metal => write!(f, "Metal"),
            BackendType::Vulkan => write!(f, "Vulkan"),
            BackendType::Cuda => write!(f, "CUDA"),
            BackendType::Cpu => write!(f, "CPU"),
        }
    }
}

/// Parameters for a text-generation or streaming inference request.
#[derive(Debug, Clone)]
pub struct InferenceParams {
    /// Unique identifier for this request (auto-generated by default).
    pub request_id: uuid::Uuid,
    /// The prompt text to send to the model.
    pub prompt: String,
    /// Sampling temperature (0.0 = deterministic, 1.0 = creative).
    pub temperature: f32,
    /// Top-p nucleus sampling threshold.
    pub top_p: f32,
    /// Maximum number of tokens to generate.
    pub max_tokens: usize,
    /// Context window size in tokens.
    pub ctx_size: u32,
}

impl Default for InferenceParams {
    fn default() -> Self {
        Self {
            request_id: uuid::Uuid::new_v4(),
            prompt: String::new(),
            temperature: 0.7,
            top_p: 0.9,
            max_tokens: 512,
            ctx_size: 2048,
        }
    }
}

/// The result of a structured-extraction call.
#[derive(Debug, Clone, PartialEq)]
pub struct ExtractionResult {
    /// Individual facts extracted from the input text.
    pub facts: Vec<String>,
}

/// Internal errors produced by LLM backend operations.
///
/// Backend implementors use this type internally. All public-facing API
/// functions return [`InferError`] — [`BackendError`] converts automatically
/// via the `From<BackendError> for InferError` impl in [`crate::error`].
#[derive(Debug, thiserror::Error)]
pub enum BackendError {
    /// Model file not found or unreadable.
    #[error("model load failed: {0}")]
    ModelLoadFailed(String),

    /// Text generation failed.
    #[error("inference failed: {0}")]
    InferenceFailed(String),

    /// Embedding generation failed.
    #[error("embedding failed: {0}")]
    EmbeddingFailed(String),

    /// Structured extraction failed.
    #[error("extraction failed: {0}")]
    ExtractionFailed(String),

    /// An inference method was called before `load_model`.
    #[error("backend not initialized — call load_model first")]
    NotInitialized,

    /// Token streaming failed.
    #[error("streaming failed: {0}")]
    StreamingFailed(String),
}

/// Trait that every LLM backend must implement.
///
/// ## Contract
///
/// - All methods are **synchronous** and may block for an extended period.
///   Callers should dispatch via `tokio::task::spawn_blocking` (or equivalent).
/// - [`load_model`](InferenceBackend::load_model) takes `&mut self` and must
///   be called once before any inference method. Perform loading before
///   wrapping the backend in an `Arc`.
/// - Implementations must satisfy `Send + Sync + 'static` so they can live
///   behind `Arc<dyn InferenceBackend + Send + Sync>` across threads.
pub trait InferenceBackend: Send + Sync + 'static {
    /// Load model weights from the GGUF file at `model_path`.
    ///
    /// `backend_type` controls GPU offloading:
    /// - [`BackendType::Metal`] / [`BackendType::Vulkan`] / [`BackendType::Cuda`] → full GPU offload
    /// - [`BackendType::Cpu`] → CPU-only inference
    fn load_model(
        &mut self,
        model_path: &Path,
        backend_type: BackendType,
    ) -> Result<(), InferError>;

    /// Returns `true` if a model has been successfully loaded.
    fn is_loaded(&self) -> bool;

    /// Returns the active compute backend type.
    ///
    /// Returns [`BackendType::Cpu`] before a model is loaded.
    fn backend_type(&self) -> BackendType;

    /// Returns the loaded model name, or `None` if no model is loaded.
    fn model_name(&self) -> Option<&str>;

    /// Generate a full text completion for the prompt in `params`.
    ///
    /// Blocks until the entire response is ready. For token-by-token
    /// incremental output use [`stream`](InferenceBackend::stream) instead.
    fn complete(&self, params: &InferenceParams) -> Result<String, InferError>;

    /// Stream a text completion one token at a time.
    ///
    /// Returns a [`mpsc::Receiver<String>`]. Tokens arrive on the channel as
    /// they are decoded; the channel is closed when generation finishes or
    /// when the receiver is dropped (cancellation).
    ///
    /// **Independent code path from [`complete`](InferenceBackend::complete).**
    fn stream(&self, params: InferenceParams) -> Result<mpsc::Receiver<String>, InferError>;

    /// Generate an embedding vector for `text`.
    ///
    /// Returns a `Vec<f32>` whose length equals the model hidden dimension.
    fn embed(&self, text: &str) -> Result<Vec<f32>, InferError>;

    /// Extract structured facts from `text`.
    ///
    /// The caller composes the full extraction prompt. Returns an
    /// [`ExtractionResult`] containing the extracted fact strings.
    fn extract(&self, text: &str) -> Result<ExtractionResult, InferError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inference_params_default_temperature() {
        assert_eq!(InferenceParams::default().temperature, 0.7);
    }

    #[test]
    fn inference_params_default_top_p() {
        assert_eq!(InferenceParams::default().top_p, 0.9);
    }

    #[test]
    fn inference_params_default_max_tokens() {
        assert_eq!(InferenceParams::default().max_tokens, 512);
    }

    #[test]
    fn inference_params_default_ctx_size() {
        assert_eq!(InferenceParams::default().ctx_size, 2048);
    }

    #[test]
    fn auto_detect_returns_valid_variant() {
        match BackendType::auto_detect() {
            BackendType::Vulkan | BackendType::Metal | BackendType::Cuda | BackendType::Cpu => {}
        }
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn macos_always_metal() {
        assert_eq!(BackendType::auto_detect(), BackendType::Metal);
    }

    #[cfg(target_os = "windows")]
    #[test]
    fn windows_cuda_or_cpu() {
        let b = BackendType::auto_detect();
        assert!(b == BackendType::Cuda || b == BackendType::Cpu);
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn linux_cuda_or_cpu() {
        let b = BackendType::auto_detect();
        assert!(b == BackendType::Cuda || b == BackendType::Cpu);
    }

    #[test]
    fn backend_type_display() {
        assert_eq!(BackendType::Metal.to_string(), "Metal");
        assert_eq!(BackendType::Cuda.to_string(), "CUDA");
        assert_eq!(BackendType::Cpu.to_string(), "CPU");
    }
}
